---
- name: Restart Keycloak
  ansible.builtin.systemd_service:
    name: jobman-keycloak
    state: restarted
  failed_when: false

- name: Restart Jobman Control
  ansible.builtin.systemd_service:
    name: jobman-control
    state: restarted
  failed_when: false
