---
collections:
  - name: ansible.posix
    version: 2.2.0
  - name: community.general
    version: 11.2.1
  - name: community.windows
    version: 3.0.1
  - name: ansible.windows
    version: 3.7.0
